# Generated by Django 5.2 on 2025-08-14 21:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Contratación'),
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_embeddings_path', models.CharField(blank=True, max_length=255, verbose_name='Ruta de Embeddings')),
                ('photos_count', models.IntegerField(default=0, verbose_name='Número de Fotos')),
                ('is_trained', models.BooleanField(default=False, verbose_name='Entrenado')),
                ('confidence_threshold', models.FloatField(default=0.9, verbose_name='Umbral de Confianza')),
                ('last_training', models.DateTimeField(blank=True, null=True, verbose_name='Último Entrenamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to='core.employee')),
            ],
            options={
                'verbose_name': 'Perfil Facial',
                'verbose_name_plural': 'Perfiles Faciales',
            },
        ),
    ]
