# Generated by Django 5.2 on 2025-08-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto principal del empleado para identificación', null=True, upload_to='employee_photos/', verbose_name='Foto del Empleado'),
        ),
    ]
