# Generated by Django 5.2 on 2025-08-15 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='area',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud'),
        ),
    ]
