# Generated by Django 5.2 on 2025-08-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_area_latitude_alter_area_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
        migrations.AlterField(
            model_name='faceprofile',
            name='confidence_threshold',
            field=models.FloatField(default=0.8, verbose_name='Umbral de Confianza'),
        ),
    ]
