# Generated by Django 5.2 on 2025-08-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_attendance_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceprofile',
            name='confidence_threshold',
            field=models.FloatField(default=0.6, verbose_name='Umbral de Confianza'),
        ),
    ]
