# Generated by Django 5.2 on 2025-08-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_faceprofile_confidence_threshold'),
        ('core', '0011_add_position_field'),
    ]

    operations = [
    ]
