# Generated by Django 5.2 on 2025-08-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20250816_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID de Empleado'),
        ),
    ]
