# Generated by Django 5.2 on 2025-08-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_change_employee_id_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
    ]
