# Generated by Django 5.2 on 2025-08-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_user_phone_employee_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceprofile',
            name='confidence_threshold',
            field=models.FloatField(default=0.9, verbose_name='Umbral de Confianza'),
        ),
    ]
