# Generated by Django 5.2 on 2025-08-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_area_latitude_alter_area_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('desarrollador', 'Desarrollador'), ('disenador', 'Diseñador'), ('secretario', 'Secretario/a'), ('gerente', 'Gerente'), ('analista', 'Analista'), ('ingeniero', 'Ingeniero'), ('contador', 'Contador'), ('recursos_humanos', 'Recursos Humanos'), ('marketing', 'Marketing'), ('ventas', 'Ventas'), ('soporte', 'Soporte Técnico'), ('administrativo', 'Administrativo'), ('operativo', 'Operativo'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Cargo'),
        ),
    ]
