# Generated by Django 5.2 on 2025-08-19 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_password_reset_token_clean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
