# Generated by Django 5.2 on 2025-08-21 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='expected_check_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Esperada de Entrada'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expected_check_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Esperada de Salida'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('desarrollador', 'Desarrollador'), ('disenador', 'Diseñador'), ('secretario', 'Secretario/a'), ('gerente', 'Gerente'), ('analista', 'Analista'), ('ingeniero', 'Ingeniero'), ('contador', 'Contador'), ('recursos_humanos', 'Recursos Humanos'), ('marketing', 'Marketing'), ('ventas', 'Ventas'), ('soporte', 'Soporte Técnico'), ('administrativo', 'Administrativo'), ('operativo', 'Operativo'), ('administrador_personal', 'Administrador de Personal'), ('asistente_rrhh', 'Asistente de RR. HH.'), ('tecnico_rrhh', 'Técnico de RR. HH.'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Cargo'),
        ),
        migrations.CreateModel(
            name='AreaSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField(verbose_name='Lunes - Hora de Entrada')),
                ('monday_end', models.TimeField(verbose_name='Lunes - Hora de Salida')),
                ('monday_active', models.BooleanField(default=True, verbose_name='Lunes Activo')),
                ('tuesday_start', models.TimeField(verbose_name='Martes - Hora de Entrada')),
                ('tuesday_end', models.TimeField(verbose_name='Martes - Hora de Salida')),
                ('tuesday_active', models.BooleanField(default=True, verbose_name='Martes Activo')),
                ('wednesday_start', models.TimeField(verbose_name='Miércoles - Hora de Entrada')),
                ('wednesday_end', models.TimeField(verbose_name='Miércoles - Hora de Salida')),
                ('wednesday_active', models.BooleanField(default=True, verbose_name='Miércoles Activo')),
                ('thursday_start', models.TimeField(verbose_name='Jueves - Hora de Entrada')),
                ('thursday_end', models.TimeField(verbose_name='Jueves - Hora de Salida')),
                ('thursday_active', models.BooleanField(default=True, verbose_name='Jueves Activo')),
                ('friday_start', models.TimeField(verbose_name='Viernes - Hora de Entrada')),
                ('friday_end', models.TimeField(verbose_name='Viernes - Hora de Salida')),
                ('friday_active', models.BooleanField(default=True, verbose_name='Viernes Activo')),
                ('saturday_start', models.TimeField(blank=True, null=True, verbose_name='Sábado - Hora de Entrada')),
                ('saturday_end', models.TimeField(blank=True, null=True, verbose_name='Sábado - Hora de Salida')),
                ('saturday_active', models.BooleanField(default=False, verbose_name='Sábado Activo')),
                ('sunday_start', models.TimeField(blank=True, null=True, verbose_name='Domingo - Hora de Entrada')),
                ('sunday_end', models.TimeField(blank=True, null=True, verbose_name='Domingo - Hora de Salida')),
                ('sunday_active', models.BooleanField(default=False, verbose_name='Domingo Activo')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15, help_text='Minutos de tolerancia antes de considerar llegada tarde', verbose_name='Tolerancia (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.area')),
            ],
            options={
                'verbose_name': 'Horario del Área',
                'verbose_name_plural': 'Horarios de las Áreas',
            },
        ),
    ]
