# Generated by Django 5.2 on 2025-08-27 02:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_schedule_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='expected_check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='expected_check_out',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=True, help_text='¿El usuario debe cambiar su contraseña en el próximo login?', verbose_name='Forzar Cambio de Contraseña'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Presente'), ('late', 'Llegada Tarde'), ('absent', 'Ausente')], default='present', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
