# Generated by Django 5.2 on 2025-08-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_attendance_expected_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(
                default=True,
                help_text='¿El usuario debe cambiar su contraseña en el próximo login?',
                verbose_name='Forzar Cambio de Contraseña'
            ),
        ),
    ]
